#!/bin/sh
sed 's/symrefBanner_glyphsend/sipush\ 4096/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC82end/sipush\ 4264/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC81end/sipush\ 4264/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC80end/sipush\ 4321/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC79end/sipush\ 4378/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC78end/sipush\ 4435/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC77end/sipush\ 4492/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC76end/sipush\ 4549/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC75end/sipush\ 4606/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC74end/sipush\ 4663/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC73end/sipush\ 4720/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC72end/sipush\ 4777/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC71end/sipush\ 4834/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC70end/sipush\ 4891/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC69end/sipush\ 4948/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC68end/sipush\ 5005/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC67end/sipush\ 5062/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC66end/sipush\ 5119/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC65end/sipush\ 5176/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC64end/sipush\ 5233/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC63end/sipush\ 5290/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC62end/sipush\ 5347/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC61end/sipush\ 5404/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC60end/sipush\ 5461/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC59end/sipush\ 5518/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC58end/sipush\ 5575/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC57end/sipush\ 5632/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC56end/sipush\ 5689/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC55end/sipush\ 5746/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC54end/sipush\ 5803/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC53end/sipush\ 5860/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC52end/sipush\ 5917/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC51end/sipush\ 5974/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC50end/sipush\ 6031/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC49end/sipush\ 6088/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC48end/sipush\ 6145/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC47end/sipush\ 6202/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC46end/sipush\ 6259/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC45end/sipush\ 6316/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC44end/sipush\ 6373/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC43end/sipush\ 6430/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC42end/sipush\ 6487/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC41end/sipush\ 6544/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC40end/sipush\ 6601/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC39end/sipush\ 6658/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC38end/sipush\ 6715/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC37end/sipush\ 6772/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC36end/sipush\ 6829/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC35end/sipush\ 6886/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC34end/sipush\ 6943/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC33end/sipush\ 7000/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC32end/sipush\ 7057/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC31end/sipush\ 7114/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC30end/sipush\ 7171/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC29end/sipush\ 7228/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC28end/sipush\ 7285/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC27end/sipush\ 7342/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC26end/sipush\ 7399/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC25end/sipush\ 7456/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC24end/sipush\ 7513/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC23end/sipush\ 7570/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC22end/sipush\ 7627/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC21end/sipush\ 7684/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC20end/sipush\ 7741/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC19end/sipush\ 7798/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC18end/sipush\ 7855/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC17end/sipush\ 7912/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC16end/sipush\ 7969/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC15end/sipush\ 8026/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC14end/sipush\ 8083/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC13end/sipush\ 8140/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC12end/sipush\ 8197/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC11end/sipush\ 8254/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC10end/sipush\ 8311/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC9end/sipush\ 8368/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC8end/sipush\ 8425/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC7end/sipush\ 8482/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC6end/sipush\ 8539/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC5end/sipush\ 8596/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC4end/sipush\ 8653/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC3end/sipush\ 8710/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC2end/sipush\ 8767/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC1end/sipush\ 8824/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC0end/sipush\ 8881/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBannerLC83end/sipush\ 8938/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symrefBanner___gnuc_va_listend/sipush\ 8939/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
sed 's/symref00000000end/sipush\ 4096/' < gglobal.s > gglobal.s.tmp
mv -f gglobal.s.tmp gglobal.s
